import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EvenTixr",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const nav = (
    <nav className="p-5 bg-white justify-between flex flex-row sticky top-0 z-30 shadow-sm">
      {/* <div>Tickets</div> */}
      <Link href="/" className="text-md">
        <Image src='/android-chrome-192x192.png' height={30} width={30}/>
      </Link>
      <div className="flex flex-row space-x-5 items-center">
        {/* <Link href='/' className="text-xs">Home</Link> */}
        <Link href="/" className="text-xs">
          Events
        </Link>
        <Link href="#contact" scroll={false} className="text-xs">
          Contact us
        </Link>

        <div>
          <svg
            width="18px"
            height="18px"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M4.78571 5H18.2251C19.5903 5 20.5542 6.33739 20.1225 7.63246L18.4558 12.6325C18.1836 13.4491 17.4193 14 16.5585 14H6.07142M4.78571 5L4.74531 4.71716C4.60455 3.73186 3.76071 3 2.76541 3H2M4.78571 5L6.07142 14M6.07142 14L6.25469 15.2828C6.39545 16.2681 7.23929 17 8.23459 17H17M17 17C15.8954 17 15 17.8954 15 19C15 20.1046 15.8954 21 17 21C18.1046 21 19 20.1046 19 19C19 17.8954 18.1046 17 17 17ZM11 19C11 20.1046 10.1046 21 9 21C7.89543 21 7 20.1046 7 19C7 17.8954 7.89543 17 9 17C10.1046 17 11 17.8954 11 19Z"
              stroke="#000000"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </div>
      </div>
    </nav>
  );
  const footer = (
    <footer
      id="contact"
      className="bg-gray-800 text-gray-300 text-xs grid grid-cols-1 md:grid-cols-2 py-3 px-10 md:px-36 gap-5"
    >
      <div className="flex flex-col ">
        {/* About Us */}
        <div className="text-white text-lg">About & Contact us</div>
        <div className="text-gray-400 text-xs mb-5">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>

        {/* Location */}
        <div className="text-white text-lg">Our Locations</div>
        <div className="text-gray-400 text-xs mb-5">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
      </div>

      <div className="flex flex-col ">
        {/* About Us */}
        <div className="text-white text-lg">How it works</div>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        {nav}
        {children}
        {footer}
      </body>
    </html>
  );
}
